{
    "formatVersion": "1.1",
    "component": {
        "group": "com.whoprnkit",
        "module": "whopreactnativekit",
        "version": "0.0.1",
        "attributes": {
            "org.gradle.status": "release"
        }
    },
    "createdBy": {
        "gradle": {
            "version": "8.14.1"
        }
    },
    "variants": [
        {
            "name": "debugVariantDefaultApiPublication",
            "attributes": {
                "com.android.build.api.attributes.BuildTypeAttr": "debug",
                "org.gradle.category": "library",
                "org.gradle.dependency.bundling": "external",
                "org.gradle.libraryelements": "aar",
                "org.gradle.usage": "java-api"
            },
            "dependencies": [
                {
                    "group": "com.facebook.react",
                    "module": "react-android",
                    "version": {
                        "requires": "0.80.0"
                    }
                },
                {
                    "group": "com.facebook.react",
                    "module": "hermes-android",
                    "version": {
                        "requires": "0.80.0"
                    }
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-stdlib",
                    "version": {
                        "requires": "2.1.20"
                    }
                }
            ],
            "files": [
                {
                    "name": "whopreactnativekit-0.0.1-debug.aar",
                    "url": "whopreactnativekit-0.0.1-debug.aar",
                    "size": 45208011,
                    "sha512": "fa154089bf71cd37fe04b29de0ad8367830525e7e8757d8cf46f71e5744436eb09a8c6272a1c825cf7d0328843d41928d0cbe9d6181c8765e2fd15303c47cae6",
                    "sha256": "78b42288adad0c8bdbc3e651f066ff19afe4cab89a19238c92e30ec4d6a13a3c",
                    "sha1": "4745869eeda867814c09a3c6d7983afe24c4b880",
                    "md5": "210aaabd418911b18a4f9b7bfa497c66"
                }
            ]
        },
        {
            "name": "debugVariantDefaultRuntimePublication",
            "attributes": {
                "com.android.build.api.attributes.BuildTypeAttr": "debug",
                "org.gradle.category": "library",
                "org.gradle.dependency.bundling": "external",
                "org.gradle.libraryelements": "aar",
                "org.gradle.usage": "java-runtime"
            },
            "dependencies": [
                {
                    "group": "androidx.appcompat",
                    "module": "appcompat",
                    "version": {
                        "requires": "1.7.0"
                    }
                },
                {
                    "group": "com.facebook.react",
                    "module": "react-android",
                    "version": {
                        "requires": "0.80.0"
                    }
                },
                {
                    "group": "com.facebook.react",
                    "module": "hermes-android",
                    "version": {
                        "requires": "0.80.0"
                    }
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-stdlib",
                    "version": {
                        "requires": "2.1.20"
                    }
                }
            ],
            "files": [
                {
                    "name": "whopreactnativekit-0.0.1-debug.aar",
                    "url": "whopreactnativekit-0.0.1-debug.aar",
                    "size": 45208011,
                    "sha512": "fa154089bf71cd37fe04b29de0ad8367830525e7e8757d8cf46f71e5744436eb09a8c6272a1c825cf7d0328843d41928d0cbe9d6181c8765e2fd15303c47cae6",
                    "sha256": "78b42288adad0c8bdbc3e651f066ff19afe4cab89a19238c92e30ec4d6a13a3c",
                    "sha1": "4745869eeda867814c09a3c6d7983afe24c4b880",
                    "md5": "210aaabd418911b18a4f9b7bfa497c66"
                }
            ]
        },
        {
            "name": "debugVariantDefaultSourcePublication",
            "attributes": {
                "com.android.build.api.attributes.BuildTypeAttr": "debug",
                "org.gradle.category": "documentation",
                "org.gradle.dependency.bundling": "external",
                "org.gradle.docstype": "sources",
                "org.gradle.usage": "java-runtime"
            },
            "files": [
                {
                    "name": "whopreactnativekit-0.0.1-debug-sources.jar",
                    "url": "whopreactnativekit-0.0.1-debug-sources.jar",
                    "size": 4710,
                    "sha512": "800e65b4ad5078dfdef3675495946bc68375ff6d5e1a16b4dc995e16bd3e954b5eb9c20e18f5978f5f99bce2ad5d52889a6141a5c800adfd10efc3eaafbb9221",
                    "sha256": "e89d94dd8c70373a7811aac2af68b5e375c2e83c1a6e5ce774ce3ba48b1340b8",
                    "sha1": "e4eb1d1197849df77979969e0c48502de961d0f2",
                    "md5": "4b1bfeba9883f60152f17588f6dcd956"
                }
            ]
        },
        {
            "name": "releaseVariantDefaultApiPublication",
            "attributes": {
                "com.android.build.api.attributes.BuildTypeAttr": "release",
                "org.gradle.category": "library",
                "org.gradle.dependency.bundling": "external",
                "org.gradle.libraryelements": "aar",
                "org.gradle.usage": "java-api"
            },
            "dependencies": [
                {
                    "group": "com.facebook.react",
                    "module": "react-android",
                    "version": {
                        "requires": "0.80.0"
                    }
                },
                {
                    "group": "com.facebook.react",
                    "module": "hermes-android",
                    "version": {
                        "requires": "0.80.0"
                    }
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-stdlib",
                    "version": {
                        "requires": "2.1.20"
                    }
                }
            ],
            "files": [
                {
                    "name": "whopreactnativekit-0.0.1-release.aar",
                    "url": "whopreactnativekit-0.0.1-release.aar",
                    "size": 6773398,
                    "sha512": "e1ada55ea87cd264f9bf07879e2526270f9e43f189b0b32e99acb1291c6aaea3b10eb770be5d2dc0d8221621950ecb29586d8eb17fcae5fca06e11523325cb52",
                    "sha256": "143f8ed6f5af6c1f4f2063602734b47b04e7685a169c2d311fffae3b20742496",
                    "sha1": "7dea423c5d7cebab82bf748832b558811044f5a2",
                    "md5": "247a31ff9265434f70da364e8d5aca4b"
                }
            ]
        },
        {
            "name": "releaseVariantDefaultRuntimePublication",
            "attributes": {
                "com.android.build.api.attributes.BuildTypeAttr": "release",
                "org.gradle.category": "library",
                "org.gradle.dependency.bundling": "external",
                "org.gradle.libraryelements": "aar",
                "org.gradle.usage": "java-runtime"
            },
            "dependencies": [
                {
                    "group": "androidx.appcompat",
                    "module": "appcompat",
                    "version": {
                        "requires": "1.7.0"
                    }
                },
                {
                    "group": "com.facebook.react",
                    "module": "react-android",
                    "version": {
                        "requires": "0.80.0"
                    }
                },
                {
                    "group": "com.facebook.react",
                    "module": "hermes-android",
                    "version": {
                        "requires": "0.80.0"
                    }
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-stdlib",
                    "version": {
                        "requires": "2.1.20"
                    }
                }
            ],
            "files": [
                {
                    "name": "whopreactnativekit-0.0.1-release.aar",
                    "url": "whopreactnativekit-0.0.1-release.aar",
                    "size": 6773398,
                    "sha512": "e1ada55ea87cd264f9bf07879e2526270f9e43f189b0b32e99acb1291c6aaea3b10eb770be5d2dc0d8221621950ecb29586d8eb17fcae5fca06e11523325cb52",
                    "sha256": "143f8ed6f5af6c1f4f2063602734b47b04e7685a169c2d311fffae3b20742496",
                    "sha1": "7dea423c5d7cebab82bf748832b558811044f5a2",
                    "md5": "247a31ff9265434f70da364e8d5aca4b"
                }
            ]
        },
        {
            "name": "releaseVariantDefaultSourcePublication",
            "attributes": {
                "com.android.build.api.attributes.BuildTypeAttr": "release",
                "org.gradle.category": "documentation",
                "org.gradle.dependency.bundling": "external",
                "org.gradle.docstype": "sources",
                "org.gradle.usage": "java-runtime"
            },
            "files": [
                {
                    "name": "whopreactnativekit-0.0.1-release-sources.jar",
                    "url": "whopreactnativekit-0.0.1-release-sources.jar",
                    "size": 4698,
                    "sha512": "b5aaa4128a8b615ad590ea246674ad270280d7f2cd8fc8f1f35a1dd8d0ac7cf126c474db07bf3d443d0e3308667d7fd96ac4d58f932dd564bb33f2d8befee939",
                    "sha256": "a51b6ec2c473dd729317640c034188563ea32146ffd3daf9e29fb6e0f30307b4",
                    "sha1": "248f7c514d88b4a0c039dfdf57ab7c80212dec35",
                    "md5": "8dad3fef67611be2158f9a054c26ee96"
                }
            ]
        }
    ]
}