{
    "formatVersion": "1.1",
    "component": {
        "group": "com.whoprnkit",
        "module": "whopreactnativekit",
        "version": "0.0.1",
        "attributes": {
            "org.gradle.status": "release"
        }
    },
    "createdBy": {
        "gradle": {
            "version": "8.14.1"
        }
    },
    "variants": [
        {
            "name": "debugVariantDefaultApiPublication",
            "attributes": {
                "com.android.build.api.attributes.BuildTypeAttr": "debug",
                "org.gradle.category": "library",
                "org.gradle.dependency.bundling": "external",
                "org.gradle.libraryelements": "aar",
                "org.gradle.usage": "java-api"
            },
            "dependencies": [
                {
                    "group": "com.facebook.react",
                    "module": "react-android",
                    "version": {
                        "requires": "0.80.0"
                    }
                },
                {
                    "group": "com.facebook.react",
                    "module": "hermes-android",
                    "version": {
                        "requires": "0.80.0"
                    }
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-stdlib",
                    "version": {
                        "requires": "2.1.20"
                    }
                }
            ],
            "files": [
                {
                    "name": "whopreactnativekit-0.0.1-debug.aar",
                    "url": "whopreactnativekit-0.0.1-debug.aar",
                    "size": 45172674,
                    "sha512": "1a770b62b88fa52d31f6ab65e0f608e499ab7678e56f5189485b965a726ad291f862ea7a4fdda643c09e484746259bfc2dc06a4216ab30aa37f4e25c03645a62",
                    "sha256": "2054475d3126ec52508cd3423f65009ffdb334cf0d81375355e09112a50436f7",
                    "sha1": "9fa45501e7f3539a2d12864b26ff6595c91ec865",
                    "md5": "1e26616c0f5baf2a8a3382fb171e97c6"
                }
            ]
        },
        {
            "name": "debugVariantDefaultRuntimePublication",
            "attributes": {
                "com.android.build.api.attributes.BuildTypeAttr": "debug",
                "org.gradle.category": "library",
                "org.gradle.dependency.bundling": "external",
                "org.gradle.libraryelements": "aar",
                "org.gradle.usage": "java-runtime"
            },
            "dependencies": [
                {
                    "group": "androidx.appcompat",
                    "module": "appcompat",
                    "version": {
                        "requires": "1.7.0"
                    }
                },
                {
                    "group": "com.facebook.react",
                    "module": "react-android",
                    "version": {
                        "requires": "0.80.0"
                    }
                },
                {
                    "group": "com.facebook.react",
                    "module": "hermes-android",
                    "version": {
                        "requires": "0.80.0"
                    }
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-stdlib",
                    "version": {
                        "requires": "2.1.20"
                    }
                }
            ],
            "files": [
                {
                    "name": "whopreactnativekit-0.0.1-debug.aar",
                    "url": "whopreactnativekit-0.0.1-debug.aar",
                    "size": 45172674,
                    "sha512": "1a770b62b88fa52d31f6ab65e0f608e499ab7678e56f5189485b965a726ad291f862ea7a4fdda643c09e484746259bfc2dc06a4216ab30aa37f4e25c03645a62",
                    "sha256": "2054475d3126ec52508cd3423f65009ffdb334cf0d81375355e09112a50436f7",
                    "sha1": "9fa45501e7f3539a2d12864b26ff6595c91ec865",
                    "md5": "1e26616c0f5baf2a8a3382fb171e97c6"
                }
            ]
        },
        {
            "name": "debugVariantDefaultSourcePublication",
            "attributes": {
                "com.android.build.api.attributes.BuildTypeAttr": "debug",
                "org.gradle.category": "documentation",
                "org.gradle.dependency.bundling": "external",
                "org.gradle.docstype": "sources",
                "org.gradle.usage": "java-runtime"
            },
            "files": [
                {
                    "name": "whopreactnativekit-0.0.1-debug-sources.jar",
                    "url": "whopreactnativekit-0.0.1-debug-sources.jar",
                    "size": 4688,
                    "sha512": "fb7cf39b0ca33b16125a0e25ba42b16e204088f1e493627a77e30aff209c560c4037ade7c2902eadf2d19f3e1057efd9b6039394162b919fde90cfdcdd2ea7af",
                    "sha256": "16cf58b43e20a370fc562d79e498b2b87d16130630e6bc5f5c258d5cdcd38afd",
                    "sha1": "b758507d7daac1bf02058a1120709902553a6c5f",
                    "md5": "87ced7c39f95579cd8fdd83dd2e3c9fb"
                }
            ]
        },
        {
            "name": "releaseVariantDefaultApiPublication",
            "attributes": {
                "com.android.build.api.attributes.BuildTypeAttr": "release",
                "org.gradle.category": "library",
                "org.gradle.dependency.bundling": "external",
                "org.gradle.libraryelements": "aar",
                "org.gradle.usage": "java-api"
            },
            "dependencies": [
                {
                    "group": "com.facebook.react",
                    "module": "react-android",
                    "version": {
                        "requires": "0.80.0"
                    }
                },
                {
                    "group": "com.facebook.react",
                    "module": "hermes-android",
                    "version": {
                        "requires": "0.80.0"
                    }
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-stdlib",
                    "version": {
                        "requires": "2.1.20"
                    }
                }
            ],
            "files": [
                {
                    "name": "whopreactnativekit-0.0.1-release.aar",
                    "url": "whopreactnativekit-0.0.1-release.aar",
                    "size": 6741227,
                    "sha512": "e9e26ff76db242c1fb2a57fc2843b04b4add0161877cb1da5e11ca529f24da399c8f98e5126a80bcd64d2b7f0a5414acd569b02ac85e491b214e5f7ca1880e4a",
                    "sha256": "af1d19829585a025c21f051d79c2c11f5b0970167d7e3df738acd042f6c51d72",
                    "sha1": "00abe402332b4f9e638591e1cc9a1c73315ae3b8",
                    "md5": "083f7c126bee0a949a5ebe43f9f208f3"
                }
            ]
        },
        {
            "name": "releaseVariantDefaultRuntimePublication",
            "attributes": {
                "com.android.build.api.attributes.BuildTypeAttr": "release",
                "org.gradle.category": "library",
                "org.gradle.dependency.bundling": "external",
                "org.gradle.libraryelements": "aar",
                "org.gradle.usage": "java-runtime"
            },
            "dependencies": [
                {
                    "group": "androidx.appcompat",
                    "module": "appcompat",
                    "version": {
                        "requires": "1.7.0"
                    }
                },
                {
                    "group": "com.facebook.react",
                    "module": "react-android",
                    "version": {
                        "requires": "0.80.0"
                    }
                },
                {
                    "group": "com.facebook.react",
                    "module": "hermes-android",
                    "version": {
                        "requires": "0.80.0"
                    }
                },
                {
                    "group": "org.jetbrains.kotlin",
                    "module": "kotlin-stdlib",
                    "version": {
                        "requires": "2.1.20"
                    }
                }
            ],
            "files": [
                {
                    "name": "whopreactnativekit-0.0.1-release.aar",
                    "url": "whopreactnativekit-0.0.1-release.aar",
                    "size": 6741227,
                    "sha512": "e9e26ff76db242c1fb2a57fc2843b04b4add0161877cb1da5e11ca529f24da399c8f98e5126a80bcd64d2b7f0a5414acd569b02ac85e491b214e5f7ca1880e4a",
                    "sha256": "af1d19829585a025c21f051d79c2c11f5b0970167d7e3df738acd042f6c51d72",
                    "sha1": "00abe402332b4f9e638591e1cc9a1c73315ae3b8",
                    "md5": "083f7c126bee0a949a5ebe43f9f208f3"
                }
            ]
        },
        {
            "name": "releaseVariantDefaultSourcePublication",
            "attributes": {
                "com.android.build.api.attributes.BuildTypeAttr": "release",
                "org.gradle.category": "documentation",
                "org.gradle.dependency.bundling": "external",
                "org.gradle.docstype": "sources",
                "org.gradle.usage": "java-runtime"
            },
            "files": [
                {
                    "name": "whopreactnativekit-0.0.1-release-sources.jar",
                    "url": "whopreactnativekit-0.0.1-release-sources.jar",
                    "size": 4676,
                    "sha512": "3bf7c6a5ab2b149f9e8b688453c50d047ee85793ccf76935abb71806d4e764431fd9838669c24bbd1f225b94e7d1b3aafd01454642f7279c51ad14240c53e93c",
                    "sha256": "bc6a3365ee1b291610dc69dfd64d0eba926a2638ccd4ae4e10b23495cee34c8e",
                    "sha1": "ba762b20929b88c9e42071170c4ed48eaf643fae",
                    "md5": "1f581e01e23d8727c8722312ec41bce7"
                }
            ]
        }
    ]
}